In [1]:
import numpy as np


In [2]:
#Python arrays.
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
#Numpy arrays whit filters.
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
#Numpy arrays with zeros
np.zeros(20)
# matrix 10 * 10 with zeros
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
#geneate normalize list
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [10]:
#Generate matrix identiti
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
#Generate random  in  range 0, 1 
np.random.rand()
 

60

In [59]:
#Random numbers in matrix 
np.random.rand(4,4)

array([[0.0776113 , 0.00175301, 0.73080979, 0.15684986],
       [0.11763207, 0.75964734, 0.94218948, 0.39448129],
       [0.63866543, 0.24982114, 0.16380331, 0.3291561 ],
       [0.22641009, 0.65239761, 0.51599794, 0.61295124]])

In [65]:
#Random number in the input range.
np.random.randint(1,20)

3

In [71]:
#Fusion the previus examples.
np.random.randint(1,100,(10,10))

array([[19, 36, 41, 15, 89, 13, 92, 36, 31, 95],
       [34, 45, 45, 85, 30, 58, 83, 75,  2, 92],
       [67, 16, 57, 88, 79, 33, 54, 15, 29, 28],
       [70, 47, 25, 44, 69,  1, 50, 18, 26, 95],
       [17, 97, 57, 16,  1, 74, 42, 92, 79, 16],
       [29, 90, 85, 16, 46,  9, 95, 54, 10, 92],
       [49, 59, 88, 97,  7, 95, 93, 34, 73, 24],
       [18, 42, 61, 19,  4,  4, 50, 96, 46, 78],
       [39, 78, 61, 22, 22, 48, 46, 17, 98, 14],
       [62, 63, 82, 15, 52, 13, 33, 19, 83,  2]])