In [1]:
import numpy as np

.copy() nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.

In [12]:
arr = np.arange(0,11)
arr_2 = arr.copy()
print(arr_2)
print(arr)
arr_2[:]= 0
print(arr_2)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[0 0 0 0 0 0 0 0 0 0 0]
[ 0  1  2  3  4  5  6  7  8  9 10]
