In [2]:
import numpy as np

SCALAR -  NO tiene dimenciones.

In [5]:
scalar = np.array(42)
print(scalar) 
print("*"*20)
scalar.ndim 
#Declarando un vector.

vector = np.array([1, 2, 3])
print(vector)
print("*"*20) 
vector.ndim 
#Declarando una matriz.

matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
print("*"*20)
matriz.ndim
#Declarando un tensor.
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
print("*"*20)
tensor.ndim

42
********************
[1 2 3]
********************
[[1 2 3]
 [4 5 6]]
********************
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
********************


3

Agregar o eliminr dimenciones.

In [6]:
vector =  np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

Agragar dimencion.

In [10]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim

[[1 2 3]]


2

Elminar dimencion

In [13]:
print(vector,vector.ndim)
vector_redux = np.squeeze(vector)
print(vector_redux, vector_redux.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


                            Reto
Definir un tensor de 5 dimensiones
Sumar una dimensión en algún eje
Borrar dimensiones que no se usen

In [31]:
tensor_five_dimensions = np.array([1,2,3,4,5,5], ndmin = 5)
tensor_more_dimensions = np.expand_dims(tensor_five_dimensions,axis = 0)
print(tensor_five_dimensions)
print(tensor_more_dimensions)
vector_redux = np.squeeze(tensor_more_dimensions)
print(vector_redux)


[[[[[1 2 3 4 5 5]]]]]
[[[[[[1 2 3 4 5 5]]]]]]
[1 2 3 4 5 5]
