In [7]:
import numpy as np
arr = np.array([13, 6, 3, 5, 10])
np.argmax(arr)

0

In [16]:
arr = np.random.randint(1,20,(3,3))


[[16  6 17]
 [12  6 11]
 [14 10 12]]


array([16, 10, 17])

MAX FUCTION

In [29]:
print(arr)
arr.max()
#Max in a row
arr.max(1)
#Max in a column.
arr.max(0)
#Position max element.
arr.argmax()

[[16  6 17]
 [12  6 11]
 [14 10 12]]


2

MIN VALUE.


In [33]:
print(arr)
arr.min()
#Min a row
arr.min(1)
#Min in a column.
arr.min(0)
#Position min element.
arr.argmin()

[[16  6 17]
 [12  6 11]
 [14 10 12]]


1

Distance in the max and min value

In [39]:
print(arr)
arr.ptp()
#In a column
arr.ptp(0)
# in a row
arr.ptp(1)

[[16  6 17]
 [12  6 11]
 [14 10 12]]


array([11,  6,  4])

Análisis estadistico.



Ordenar elementos.

In [67]:
arr = np.random.randint(1,20,(20))
print(arr)
arr_ordenado = np.sort(arr)
arr_ordenado

[14  3  6  8 14  6  4  2 18  3 18 18  3 15 19 15 10  9  2 17]


array([ 2,  2,  3,  3,  3,  4,  6,  6,  8,  9, 10, 14, 14, 15, 15, 17, 18,
       18, 18, 19])

In [68]:
#get a percentile.
np.percentile(arr, 0)
#get a median
np.median(arr)
#get a standard deviation.
np.std(arr)
#get a variance.
np.var(arr)
#get a  average.
np.mean(arr) 


10.2