In [2]:
import numpy as np

    Shape.  Indica la forma del arreglo.
    

In [4]:
arr = np.random.randint(1,10,(4,3))
print(arr)
arr.shape



[[1 1 3]
 [3 6 4]
 [1 4 1]
 [5 7 9]]


(4, 3)


Transforma el arreglo mientras se mantengan los elementos.

In [12]:
print(arr)
arr.reshape(1,12)

[[4 1 7]
 [3 6 2]
 [7 9 5]
 [8 8 5]]


array([[4, 1, 7, 3, 6, 2, 7, 9, 5, 8, 8, 5]])

 Reshape like in c

In [20]:
print(arr)
np.reshape(arr,(6,2),"C")

[[4 1 7]
 [3 6 2]
 [7 9 5]
 [8 8 5]]


array([[4, 1],
       [7, 3],
       [6, 2],
       [7, 9],
       [5, 8],
       [8, 5]])

 Reshape like in fortran

In [21]:
print(arr)
np.reshape(arr,(6,2),"F")

[[4 1 7]
 [3 6 2]
 [7 9 5]
 [8 8 5]]


array([[4, 9],
       [3, 8],
       [7, 7],
       [8, 2],
       [1, 5],
       [6, 5]])